INSERT INTO breed (name) values('Labrador Retriever');
INSERT INTO breed (name) values('German Shepherd Dog');
INSERT INTO breed (name) values('Poodle');
INSERT INTO breed (name) values('Chihuahua');
INSERT INTO breed (name) values('Golden Retriever');
INSERT INTO breed (name) values('Yorkshire Terrier');
INSERT INTO breed (name) values('Dachshund');
INSERT INTO breed (name) values('Beagle');
INSERT INTO breed (name) values('Boxer');
INSERT INTO breed (name) values('Miniature Schnauzer');
INSERT INTO breed (name) values('Shih Tzu');
INSERT INTO breed (name) values('Bulldog');
INSERT INTO breed (name) values('German Spitz');
INSERT INTO breed (name) values('English Cocker Spaniel');
INSERT INTO breed (name) values('Cavalier King Charles Spaniel');
INSERT INTO breed (name) values('French Bulldog');
INSERT INTO breed (name) values('Pug');
INSERT INTO breed (name) values('Rottweiler');
INSERT INTO breed (name) values('English Setter');
INSERT INTO breed (name) values('Maltese');
INSERT INTO breed (name) values('English Springer Spaniel');
INSERT INTO breed (name) values('German Shorthaired Pointer');
INSERT INTO breed (name) values('Staffordshire Bull Terrier');
INSERT INTO breed (name) values('Border Collie');
INSERT INTO breed (name) values('Shetland Sheepdog');
INSERT INTO breed (name) values('Dobermann');
INSERT INTO breed (name) values('West Highland White Terrier');
INSERT INTO breed (name) values('Bernese Mountain Dog');
INSERT INTO breed (name) values('Great Dane');
INSERT INTO breed (name) values('Brittany Spaniel');